#
###################################
# Site wide configuration
####################################
#
title:       "Andrey codes"
description: 'Insights in .NET, Machine Learning and software product development.'
# the base hostname & protocol for your site
url:         https://amironoff.github.io

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Riga
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false
# Build settings
markdown: kramdown
theme: leonids
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Andrey Mironoff
  avatar: #avatar.jpg
  job: "Programmer/Entrepreneur"
  bio: #"I code stuff. That involves using C#, .NET & Python, applying machine learning to build NLP solutions, and sometimes building a company from scratch."
  email: #mail@mail.com
  disqus-shortname: #renyuanzblog
  twitter: #renyuan814 #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: amironoff
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username